# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf2d380138aab02ba39114f7dfc347659fe179f3400a8c0f1329e5ad1908bc8007f4c6e12091045d18305cbc60233a3ec077452daf3f002180b783147c415cac

test:
  secret_key_base: ce6984ddeca6ff38bb330f9a938bf05dffbc34ba67f1704b63ef4abb9e2750a8155856d78a93d9d3c76ec14f5392e78122bc4f044aaaa15717f7a3096caf000e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
